Refactor: adapt greenbone-nvt-sync to new feed structure

diff --git a/tools/greenbone-nvt-sync.in b/tools/greenbone-nvt-sync.in
--- a/tools/greenbone-nvt-sync.in
+++ b/tools/greenbone-nvt-sync.in
@@ -22,6 +22,10 @@
 
 VERSION=@OPENVAS_VERSION@
 
+VERSION_MAYOR=`echo $VERSION | cut -d. -f1`
+VERSION_MINOR=`echo $VERSION | cut -d. -f2`
+VERSION_SHORT="$VERSION_MAYOR.$VERSION_MINOR"
+
 # SETTINGS
 # ========
 
@@ -86,6 +90,12 @@ ENABLED=1
 # disabled.
 LOG_CMD="logger -t $SCRIPT_NAME"
 
+[ -z "$DATA_BASE_PATH" ] && DATA_BASE_PATH="/community/community/vulnerability-feed/$VERSION_SHORT"
+[ -z "$NASL_DATA_PATH" ] && NASL_DATA_PATH="$DATA_BASE_PATH/vt-data/nasl/"
+[ -z "$NOTUS_DATA_PATH" ] && NOTUS_DATA_PATH="$DATA_BASE_PATH/vt-data/notus/"
+
+[ -z "$RSYNC_DOMAIN" ] && RSYNC_DOMAIN=feed.community.greenbone.net
+
 check_logger () {
   logger --socket-error=on -p daemon.info -t $SCRIPT_NAME "Checking logger" --no-act 1>/dev/null 2>&1
   if [ $? -gt 0 ]
@@ -105,6 +115,8 @@ if [ -z "$NVT_DIR" ]
 then
   NVT_DIR="@OPENVAS_NVT_DIR@"
 fi
+
+[ -z "$NOTUS_DIR" ] && NOTUS_DIR="/var/lib/notus"
 
 log_write () {
   $LOG_CMD -p daemon.notice $1
@@ -180,6 +192,13 @@ fi
 # This also ensures variables like FEED_PRESENT are set.
 get_feed_info
 
+if [ -z "$COMMUNITY_NVT_RSYNC_FEED" ]; then
+	COMMUNITY_NVT_RSYNC_FEED=rsync://$RSYNC_DOMAIN:$NASL_DATA_PATH
+fi
+if [ -z "$COMMUNITY_NOTUS_RSYNC_FEED" ]; then
+	COMMUNITY_NOTUS_RSYNC_FEED=rsync://$RSYNC_DOMAIN:$NOTUS_DATA_PATH
+fi
+
 # Determine whether a GSF access key is present. If yes,
 # then use the Greenbone Security Feed. Else use the
 # Greenbone Community Feed.
@@ -189,11 +208,6 @@ then
 else
   RESTRICTED=0
 
-  if [ -z "$COMMUNITY_NVT_RSYNC_FEED" ]; then
-    COMMUNITY_NVT_RSYNC_FEED=rsync://feed.community.greenbone.net:/nvt-feed
-    # An alternative syntax which might work if the above doesn't:
-    # COMMUNITY_NVT_RSYNC_FEED=rsync@feed.community.greenbone.net::/nvt-feed
-  fi
 fi
 
 RSYNC=`command -v rsync`
@@ -351,9 +365,16 @@ do_rsync_community_feed () {
   sleep 5
   log_notice "Configured NVT rsync feed: $COMMUNITY_NVT_RSYNC_FEED"
   mkdir -p "$NVT_DIR"
-  eval "$RSYNC -ltvrP $RSYNC_DELETE $RSYNC_CHMOD \"$COMMUNITY_NVT_RSYNC_FEED\" \"$NVT_DIR\" --exclude=plugin_feed_info.inc"
+  log_notice "Loading NASL data to $NVT_DIR"
+  $RSYNC -ltvrP $RSYNC_DELETE $RSYNC_CHMOD "$COMMUNITY_NVT_RSYNC_FEED" "$NVT_DIR" --exclude=plugin_feed_info.inc
   if [ $? -ne 0 ] ; then
-    log_err "rsync failed."
+    log_err "rsync for nasl failed."
+    exit 1
+  fi
+  log_notice "Loading Notus data to $NOTUS_DIR"
+  $RSYNC -ltvrP $RSYNC_DELETE $RSYNC_CHMOD "$COMMUNITY_NOTUS_RSYNC_FEED" "$NOTUS_DIR"
+  if [ $? -ne 0 ] ; then
+    log_err "rsync for notus failed."
     exit 1
   fi
   # Sleep for five seconds (after the above rsync call) to prevent IP blocking due
@@ -522,6 +543,7 @@ do_help () {
   echo " --help         display this help"
   echo " --identify     display information"
   echo " --nvtdir dir   set dir as NVT directory"
+  echo " --notusdir dir   set dir as NOTUS directory"
   echo " --selftest     perform self-test and set exit code"
   echo " --verbose      makes the sync process print details"
   echo " --version      display version"
@@ -563,6 +585,10 @@ while test $# -gt 0; do
       ;;
     --nvt-dir)
       NVT_DIR="$2"
+      shift
+      ;;
+    --notus-dir)
+      NOTUS_DIR="$2"
       shift
       ;;
     --feedcurrent)
