* tools/greenbone-nvt-sync.in (is_feed_current): Remove non-portable negative return code, log an error and exit non-zero instead for consistency.
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-scanner@27451 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/greenbone-nvt-sync.in b/tools/greenbone-nvt-sync.in
--- a/tools/greenbone-nvt-sync.in
+++ b/tools/greenbone-nvt-sync.in
@@ -361,10 +361,10 @@ is_feed_current () {
 
     if [ -z "$FEED_VERSION_SERVER" ]
     then
-      echo "Could not determine server feed version."
+      log_err "Could not determine server feed version."
       rm -rf $FEED_INFO_TEMP_DIR
       cleanup_temp_access_key
-      return -1
+      exit 1
     fi
     # Check against FEED_VERSION
     if [ $FEED_VERSION -lt $FEED_VERSION_SERVER ] ; then
