* tools/greenbone-nvt-sync.in (do_wget_community_feed): Log error and 	exit on failure. 	(do_curl_community_feed): Add missing definition of TMP_NVT.  Log error 	and exit on failure.
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-scanner@26402 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/greenbone-nvt-sync.in b/tools/greenbone-nvt-sync.in
--- a/tools/greenbone-nvt-sync.in
+++ b/tools/greenbone-nvt-sync.in
@@ -370,23 +370,63 @@ do_wget_community_feed () {
 
   log_info "Configured NVT http feed: $COMMUNITY_NVT_HTTP_FEED"
   log_info "Downloading to: $TMP_NVT"
-  mkdir -p "$NVT_DIR" \
-    && wget "$COMMUNITY_NVT_HTTP_FEED" -O $TMP_NVT \
-    && cd "$NVT_DIR" \
-    && tar xvjf $TMP_NVT \
-    && rm -f $TMP_NVT \
-    && log_info "Download complete"
+  mkdir -p "$NVT_DIR"
+
+  wget "$COMMUNITY_NVT_HTTP_FEED" -O $TMP_NVT
+
+  if [ $? -ne 0 ]
+  then
+    rm -f $TMP_NVT
+    log_err "wget failed"
+    exit 1
+  else
+    log_info "Download complete"
+  fi
+
+  cd "$NVT_DIR" \
+    && tar xvjf $TMP_NVT
+
+  if [ $? -ne 0 ]
+  then
+    rm -f $TMP_NVT
+    log_err "tar extraction failed."
+    exit 1
+  else
+    rm -f $TMP_NVT
+    log_info "NVTs extracted successfully"
+  fi
 }
 
 do_curl_community_feed () {
+  TMP_NVT="$SYNC_TMP_DIR/openvas-feed-`date +%F`-$$.tar.bz2"
+
   log_info "Configured NVT http feed: $COMMUNITY_NVT_HTTP_FEED"
   log_info "Downloading to: $TMP_NVT"
-  mkdir -p "$NVT_DIR" \
-    && curl "$COMMUNITY_NVT_HTTP_FEED" -o $TMP_NVT \
-    && cd "$NVT_DIR" \
-    && tar xvjf $TMP_NVT \
-    && rm -f $TMP_NVT \
-    && log_info "Download complete"
+  mkdir -p "$NVT_DIR"
+
+  curl "$COMMUNITY_NVT_HTTP_FEED" -o $TMP_NVT
+
+  if [ $? -ne 0 ]
+  then
+    rm -f $TMP_NVT
+    log_err "curl failed"
+    exit 1
+  else
+    log_info "Download complete"
+  fi
+
+  cd "$NVT_DIR" \
+    && tar xvjf $TMP_NVT
+
+  if [ $? -ne 0 ]
+  then
+    rm -f $TMP_NVT
+    log_err "tar extraction failed."
+    exit 1
+  else
+    rm -f $TMP_NVT
+    log_info "NVTs extracted successfully"
+  fi
 }
 
 do_rsync_community_feed () {
