Bugfix in mktemp
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-scanner@7074 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/openvas-nvt-sync.in b/tools/openvas-nvt-sync.in
--- a/tools/openvas-nvt-sync.in
+++ b/tools/openvas-nvt-sync.in
@@ -60,7 +60,7 @@ if [ -z "$TMPDIR" ]; then
 	SYNC_TMP_DIR=/tmp
 # If we have mktemp, create a temporary dir (safer)
         if [ -n "`which mktemp`" ]; then
-            SYNC_TMP_DIR=`mktemp -d openvas-nvt-sync` || { echo "ERROR: Cannot create temporary directory for file download" >&2; exit 1 ; }
+            SYNC_TMP_DIR=`mktemp -d openvas-nvt-sync.XXXXXXXXXX` || { echo "ERROR: Cannot create temporary directory for file download" >&2; exit 1 ; }
             trap "rm -rf $SYNC_TMP_DIR" 0 1 2 5 15
         fi
 else
