* tools/openvas-nvt-sync.in: Ensure openvas-nvt-sync syncs into the   NVT directory configured in the scanner by default. Remove obsolete   comment.
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-scanner@10719 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/openvas-nvt-sync.in b/tools/openvas-nvt-sync.in
--- a/tools/openvas-nvt-sync.in
+++ b/tools/openvas-nvt-sync.in
@@ -32,12 +32,15 @@
 # if you need to debug script
 # set -x
 
-# these locations should be correct if standard ./configure had
-# been applied.
-
 # configure NVT_DIR where we will sync NVTs
 if [ -z "$NVT_DIR" ]; then
-  NVT_DIR="@OPENVAS_NVT_DIR@"
+  OPENVASSD=`which openvassd`
+  if [ -z "$OPENVASSD" ] ; then
+    echo "[e] Error: openvassd is not in the path, could not determine NVT directory."
+    exit 1
+  else
+    NVT_DIR=`openvassd -s | awk -F" = " '/^plugins_folder/ { print $2 }'`
+  fi
 fi
 
 # Script and feed information which will be made available to user through
