* tools/openvas-nvt-sync.in: Make indentation consistent, flush   trailing spaces.
git-svn-id: svn+ssh://scm.wald.intevation.org/openvas/trunk/openvas-scanner@10641 423fd1db-d629-0410-8442-d21db03e70f4

diff --git a/tools/openvas-nvt-sync.in b/tools/openvas-nvt-sync.in
--- a/tools/openvas-nvt-sync.in
+++ b/tools/openvas-nvt-sync.in
@@ -12,7 +12,7 @@
 # Vlatko Kosturjak <kost@linux.hr>
 # Michael Wiegand <michael.wiegand@greenbone.net>
 #
-# Script is complete rewrite of original sync script by 
+# Script is complete rewrite of original sync script by
 # Lukas Grunwald <l.grunwald@dn-systems.de>
 # Jan-Oliver Wagner <jan-oliver.wagner@intevation.de>
 #
@@ -37,7 +37,7 @@
 
 # configure NVT_DIR where we will sync NVTs
 if [ -z "$NVT_DIR" ]; then
-	NVT_DIR="@OPENVAS_NVT_DIR@"
+  NVT_DIR="@OPENVAS_NVT_DIR@"
 fi
 
 # Script and feed information which will be made available to user through
@@ -71,47 +71,47 @@ fi
 
 # The URL of the plugin feed
 if [ -z "$OV_RSYNC_FEED" ]; then
-	OV_RSYNC_FEED=rsync://rsync.openvas.org:/nvt-feed
-	# An alternative syntax which might work if the above doesn't:
-	# OV_RSYNC_FEED=rsync@rsync.openvas.org::nvt-feed
+  OV_RSYNC_FEED=rsync://rsync.openvas.org:/nvt-feed
+  # An alternative syntax which might work if the above doesn't:
+  # OV_RSYNC_FEED=rsync@rsync.openvas.org::nvt-feed
 fi
 
 if [ -z "$OV_HTTP_FEED" ]; then
-	OV_HTTP_FEED=http://www.openvas.org/openvas-nvt-feed-current.tar.bz2
+  OV_HTTP_FEED=http://www.openvas.org/openvas-nvt-feed-current.tar.bz2
 fi
 
 if [ -z "$TMPDIR" ]; then
-	SYNC_TMP_DIR=/tmp
-# If we have mktemp, create a temporary dir (safer)
-        if [ -n "`which mktemp`" ]; then
-            SYNC_TMP_DIR=`mktemp -d openvas-nvt-sync.XXXXXXXXXX -t` || { echo "ERROR: Cannot create temporary directory for file download" >&2; exit 1 ; }
-            trap "rm -rf $SYNC_TMP_DIR" EXIT HUP INT TRAP TERM
-        fi
+  SYNC_TMP_DIR=/tmp
+  # If we have mktemp, create a temporary dir (safer)
+  if [ -n "`which mktemp`" ]; then
+    SYNC_TMP_DIR=`mktemp -d openvas-nvt-sync.XXXXXXXXXX -t` || { echo "ERROR: Cannot create temporary directory for file download" >&2; exit 1 ; }
+    trap "rm -rf $SYNC_TMP_DIR" EXIT HUP INT TRAP TERM
+  fi
 else
-	SYNC_TMP_DIR="$TMPDIR"
+  SYNC_TMP_DIR="$TMPDIR"
 fi
 
 do_help () {
-	echo "$0: Sync NVTs using different protocols"
-	echo " --rsync		sync with rsync (default)"
-	echo " --wget		sync with wget"
-	echo " --curl		sync with curl"
-	echo " --check		just checksum check"
-	echo "OpenVAS administrator functions:"
-	echo " --selftest	perform self-test"
-	echo " --identify	display information"
-	echo " --version	display version"
-	echo " --describe	display current feed info"
-	echo " --nvt-dir <dir>	directory of the NVT collection"
-	echo ""
-	echo "Environment variables:"
-	echo "NVT_DIR		where to extract plugins (absolute path)"
-	echo "OV_RSYNC_FEED	URL of rsync feed" 
-	echo "OV_HTTP_FEED	URL of http feed"
-	echo "TMPDIR		temporary directory used to download the files"
-	echo "Note that you can use standard ones as well (e.g. http_proxy) for wget/curl"
-	echo ""
-	exit 0
+  echo "$0: Sync NVTs using different protocols"
+  echo " --rsync		sync with rsync (default)"
+  echo " --wget		sync with wget"
+  echo " --curl		sync with curl"
+  echo " --check		just checksum check"
+  echo "OpenVAS administrator functions:"
+  echo " --selftest	perform self-test"
+  echo " --identify	display information"
+  echo " --version	display version"
+  echo " --describe	display current feed info"
+  echo " --nvt-dir <dir>	directory of the NVT collection"
+  echo ""
+  echo "Environment variables:"
+  echo "NVT_DIR		where to extract plugins (absolute path)"
+  echo "OV_RSYNC_FEED	URL of rsync feed"
+  echo "OV_HTTP_FEED	URL of http feed"
+  echo "TMPDIR		temporary directory used to download the files"
+  echo "Note that you can use standard ones as well (e.g. http_proxy) for wget/curl"
+  echo ""
+  exit 0
 }
 
 CMD_RSYNC=`which rsync`
@@ -121,108 +121,108 @@ CMD_CURL=`which curl`
 TMP_NVT="$SYNC_TMP_DIR/openvas-feed-`date +%F`-$$.tar.bz2"
 
 chk_system_tools () {
-	echo "[i] Searching for required system tools (look for warnings)..."
+  echo "[i] Searching for required system tools (look for warnings)..."
 
-	if [ -z "$CMD_MD5SUM" ]; then
-	  SELFTEST_FAIL=1
-	  echo "[w] Warning: MD5SUM not found";
-	fi
+  if [ -z "$CMD_MD5SUM" ]; then
+    SELFTEST_FAIL=1
+    echo "[w] Warning: MD5SUM not found";
+  fi
 
-	if [ -z "$CMD_RSYNC" ]; then
-	  echo "[w] Warning: RSYNC not found";
-	fi
+  if [ -z "$CMD_RSYNC" ]; then
+    echo "[w] Warning: RSYNC not found";
+  fi
 
-	if [ -z "$CMD_WGET" ]; then
-	  echo "[w] Warning: wget not found";
-	fi
+  if [ -z "$CMD_WGET" ]; then
+    echo "[w] Warning: wget not found";
+  fi
 
-	if [ -z "$CMD_CURL" ]; then
-	  echo "[w] Warning: curl not found";
-	fi
+  if [ -z "$CMD_CURL" ]; then
+    echo "[w] Warning: curl not found";
+  fi
 
-	if [ -z "$CMD_RSYNC" -a -z "$CMD_WGET" -a -z "$CMD_CURL" ]; then
-	  SELFTEST_FAIL=1
-	fi
+  if [ -z "$CMD_RSYNC" -a -z "$CMD_WGET" -a -z "$CMD_CURL" ]; then
+    SELFTEST_FAIL=1
+  fi
 
-	echo "[i] If you did not get any warnings, that means you have all tools required"
+  echo "[i] If you did not get any warnings, that means you have all tools required"
 
-	echo "[i] Note that it is recommended to have md5sum and one of the following: rsync, wget or curl."
+  echo "[i] Note that it is recommended to have md5sum and one of the following: rsync, wget or curl."
 }
 
 do_rsync () {
-	if [ -z "$CMD_RSYNC" ]; then
-		echo "[w] rsync not found!"
-	else
-		echo "[i] Using rsync: $CMD_RSYNC"
-		echo "[i] Configured NVT rsync feed: $OV_RSYNC_FEED"
-		mkdir -p "$NVT_DIR"
-		eval "$CMD_RSYNC -ltvrP \"$OV_RSYNC_FEED\" \"$NVT_DIR\""
-		if [ $? -ne 0 ] ; then
-			echo "Error: rsync failed. Your NVT collection might be broken now."
-			exit 1
-		fi
-	fi
+  if [ -z "$CMD_RSYNC" ]; then
+    echo "[w] rsync not found!"
+  else
+    echo "[i] Using rsync: $CMD_RSYNC"
+    echo "[i] Configured NVT rsync feed: $OV_RSYNC_FEED"
+    mkdir -p "$NVT_DIR"
+    eval "$CMD_RSYNC -ltvrP \"$OV_RSYNC_FEED\" \"$NVT_DIR\""
+    if [ $? -ne 0 ] ; then
+      echo "Error: rsync failed. Your NVT collection might be broken now."
+      exit 1
+    fi
+  fi
 }
 
 do_wget () {
-	if [ -z "$CMD_WGET" ]; then
-		echo "[w] GNU wget not found!"
-	else
-		echo "[i] Using GNU wget: $CMD_WGET"
-		echo "[i] Configured NVT http feed: $OV_HTTP_FEED"
-		echo "[i] Downloading to: $TMP_NVT"
-		mkdir -p "$NVT_DIR" \
-		&& wget "$OV_HTTP_FEED" -O $TMP_NVT \
-		&& cd "$NVT_DIR" \
-		&& tar xvjf $TMP_NVT \
-		&& rm -f $TMP_NVT \
-		&& echo "[i] Download complete"
-	fi
+  if [ -z "$CMD_WGET" ]; then
+    echo "[w] GNU wget not found!"
+  else
+    echo "[i] Using GNU wget: $CMD_WGET"
+    echo "[i] Configured NVT http feed: $OV_HTTP_FEED"
+    echo "[i] Downloading to: $TMP_NVT"
+    mkdir -p "$NVT_DIR" \
+    && wget "$OV_HTTP_FEED" -O $TMP_NVT \
+    && cd "$NVT_DIR" \
+    && tar xvjf $TMP_NVT \
+    && rm -f $TMP_NVT \
+    && echo "[i] Download complete"
+  fi
 }
 
 do_curl () {
-	if [ -z "$CMD_CURL" ]; then 
-		echo "[w] curl not found!"
-	else
-		echo "[i] Using curl: $CMD_CURL"
-		echo "[i] Configured NVT http feed: $OV_HTTP_FEED"
-		echo "[i] Downloading to: $TMP_NVT"
-		mkdir -p "$NVT_DIR" \
-		&& curl "$OV_HTTP_FEED" -o $TMP_NVT \
-		&& cd "$NVT_DIR" \
-		&& tar xvjf $TMP_NVT \
-		&& rm -f $TMP_NVT \
-		&& echo "[i] Download complete"
-	fi
+  if [ -z "$CMD_CURL" ]; then
+    echo "[w] curl not found!"
+  else
+    echo "[i] Using curl: $CMD_CURL"
+    echo "[i] Configured NVT http feed: $OV_HTTP_FEED"
+    echo "[i] Downloading to: $TMP_NVT"
+    mkdir -p "$NVT_DIR" \
+    && curl "$OV_HTTP_FEED" -o $TMP_NVT \
+    && cd "$NVT_DIR" \
+    && tar xvjf $TMP_NVT \
+    && rm -f $TMP_NVT \
+    && echo "[i] Download complete"
+  fi
 }
 
 do_check_md5 () {
-	if [ -z "CMD_MD5SUM" ]; then
-		echo "[w] md5sum utility not found, cannot check NVT checksums! You've been warned!"
-	else
-		echo -n "[i] Checking dir: "	
-		eval "cd \"$NVT_DIR\""
-		if [ $? -ne 0 ] ; then
-			echo "not ok"
-			echo "Check your NVT dir for existence and permissions!"
-			exit 1
-		else
-			echo "ok"
-		fi
-		echo -n "[i] Checking MD5 checksum: "	
-		eval "cd \"$NVT_DIR\" ; $CMD_MD5SUM -c --status \"$NVT_DIR/md5sums\""
-		if [ $? -ne 0 ] ; then
-			echo "not ok"
-			echo "Error: md5sums not correct. Your NVT collection might be broken now."
-			echo "Please try this for details: cd \"$NVT_DIR\" ; $CMD_MD5SUM -c \"$NVT_DIR/md5sums\" | less"
-			exit 1
-		fi
-		echo "ok"
-	fi
+  if [ -z "CMD_MD5SUM" ]; then
+    echo "[w] md5sum utility not found, cannot check NVT checksums! You've been warned!"
+  else
+    echo -n "[i] Checking dir: "
+    eval "cd \"$NVT_DIR\""
+    if [ $? -ne 0 ] ; then
+      echo "not ok"
+      echo "Check your NVT dir for existence and permissions!"
+      exit 1
+    else
+      echo "ok"
+    fi
+    echo -n "[i] Checking MD5 checksum: "
+    eval "cd \"$NVT_DIR\" ; $CMD_MD5SUM -c --status \"$NVT_DIR/md5sums\""
+    if [ $? -ne 0 ] ; then
+      echo "not ok"
+      echo "Error: md5sums not correct. Your NVT collection might be broken now."
+      echo "Please try this for details: cd \"$NVT_DIR\" ; $CMD_MD5SUM -c \"$NVT_DIR/md5sums\" | less"
+      exit 1
+    fi
+    echo "ok"
+  fi
 }
 
 do_self_test () {
-	chk_system_tools
+  chk_system_tools
 }
 
 do_describe () {
@@ -253,7 +253,7 @@ do_sync () {
       echo "[w] GNU wget not found!"
       if [ -z "$CMD_CURL"]; then
         echo "[w] curl not found!"
-        echo -n "[e] no utility available in PATH environment variable to download plugins"  
+        echo -n "[e] no utility available in PATH environment variable to download plugins"
         exit 1
       else
         echo "[i] Will use curl"
@@ -270,59 +270,59 @@ do_sync () {
 }
 
 if [ -n "$1" ]; then
-	while test $# -gt 0; do
-	 case "$1" in
-		--help)
-			do_help
-			exit 0
-			;;
-		--rsync)
-			do_rsync
-			do_check_md5
-			exit 0
-			;;
-		--wget)
-			do_wget
-			do_check_md5
-			exit 0
-			;;
-		--curl)
-			do_curl
-			do_check_md5
-			exit 0
-			;;
-		--check)
-			do_check_md5
-			exit 0
-			;;
-		--version)
-			echo $VERSION
-			exit 0
-			;;
-		--identify)
-			echo "NVTSYNC|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|NVTSYNC"
-			exit 0
-			;;
-		--selftest)
-			SELFTEST_FAIL=0
-			do_self_test
-			exit $SELFTEST_FAIL
-			;;
-		--describe)
-			do_describe
-			exit 0
-			;;
-		--feedversion)
-			do_feedversion
-			exit 0
-			;;
-		--nvt-dir)
-			NVT_DIR="$2"
-			shift
-			;;
-	 esac
-	 shift
-	done
+  while test $# -gt 0; do
+    case "$1" in
+      --help)
+        do_help
+        exit 0
+        ;;
+      --rsync)
+        do_rsync
+        do_check_md5
+        exit 0
+        ;;
+      --wget)
+        do_wget
+        do_check_md5
+        exit 0
+        ;;
+      --curl)
+        do_curl
+        do_check_md5
+        exit 0
+        ;;
+      --check)
+        do_check_md5
+        exit 0
+        ;;
+      --version)
+        echo $VERSION
+        exit 0
+        ;;
+      --identify)
+        echo "NVTSYNC|$SCRIPT_NAME|$VERSION|$FEED_NAME|$RESTRICTED|NVTSYNC"
+        exit 0
+        ;;
+      --selftest)
+        SELFTEST_FAIL=0
+        do_self_test
+        exit $SELFTEST_FAIL
+        ;;
+      --describe)
+        do_describe
+        exit 0
+        ;;
+      --feedversion)
+        do_feedversion
+        exit 0
+        ;;
+      --nvt-dir)
+        NVT_DIR="$2"
+        shift
+        ;;
+    esac
+    shift
+  done
 fi
 
 show_intro
